name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "hello, world!"

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Test
        run: echo "Testando :D"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Deploy
        run: echo "Terminou!"
